# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGvy8RbAnnGmzWb-C1apugoSlScw7Y7d
"""

'''Problem Statement

A financial research company wants to analyze historical NIFTY 50 market data to understand:

Overall market trend
Price movement
Trading volume behavior
Market volatility
Best and worst trading periods
Business insights for investors

The goal is to convert raw market data into meaningful business insights using Data Analytics.'''

'''Project Objectives
Understand historical market performance.
Clean and preprocess stock market data.
Perform Exploratory Data Analysis (EDA).
Create meaningful business KPIs.
Visualize trends and patterns.
Generate business insights for investment decisions.'''

#part 1 ========================================
# Import Libraries
# ========================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

print("Libraries Imported Successfully")

df=pd.read_csv('/content/NIFTY50.csv')

df

df.head()

#Dataset Shape
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

#Column Names
df.columns

#Dataset Information
df.info()

#Statistical Summary
df.describe().T

#Missing Values
df.isnull().sum()

#Duplicate Records
df.duplicated().sum()

#Remove Duplicates
df = df.drop_duplicates()

print("Duplicates Removed")

#Convert Date
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

#Check Datatype Again
df.dtypes

#Sort Dataset
df = df.sort_values("Date")

#Reset Index
df.reset_index(drop=True, inplace=True)

#Final Dataset Preview
df.head()

#Create Year
df["Year"] = df["Date"].dt.year

#Create Month
df["Month"] = df["Date"].dt.month_name()

#Quarter
df["Quarter"] = df["Date"].dt.quarter

#Weekday
df["Weekday"] = df["Date"].dt.day_name()

#Check New Dataset
df.head()

import os

#Save Clean Dataset
if not os.path.exists('data'):
    os.makedirs('data')
df.to_csv('data/NIFTY50_Cleaned.csv', index=False)

#Initial EDA
#Number of Trading Days Per Year
df["Year"].value_counts().sort_index()

#Number of Trading Days Per Month
df["Month"].value_counts()

#rading Days by Quarter
df["Quarter"].value_counts()

#Trading Days by Weekday
df["Weekday"].value_counts()

"""Business Insights (Part 1)
Dataset contains approximately 16 years of historical NIFTY 50 trading data.
Date column has been converted into datetime format for time-series analysis.
Additional calendar features (Year, Month, Quarter, Weekday) have been created for business analysis.
Duplicate records have been removed.
The cleaned dataset has been saved for further analysis.'''

'''In Part 2, we will build Feature Engineering similar to your Supply Chain project, including:

Daily Return
Price Change
Daily Range
High-Low %
Open-Close %
20-Day Moving Average
50-Day Moving Average
Volatility
Cumulative Return

Along with 10–15 business KPIs and deeper statistical analysis.'''

#Part 2 – Feature Engineering & Business KPIs

# Daily Price Change
df["Price Change"] = df["Close"] - df["Open"]

df.head()

#Daily Return (%)
# Daily Return Percentage

df["Daily Return (%)"] = ((df["Close"]-df["Open"])/df["Open"])*100

df.head()

# Daily Trading Range

df["Daily Range"] = df["High"]-df["Low"]

#High-Low Percentage
df["High-Low (%)"] = ((df["High"]-df["Low"])/df["Low"])*100

#Open-Close Percentage
df["Open-Close (%)"] = ((df["Close"]-df["Open"])/df["Open"])*100

#20-Day Moving Average
#Business Use
#Short-term trend identify

df["20 Day MA"] = df["Close"].rolling(window=20).mean()

#50-Day Moving Average
#Medium-term trend identify
df["50 Day MA"] = df["Close"].rolling(window=50).mean()

#100-Day Moving Average
df["100 Day MA"] = df["Close"].rolling(window=100).mean()

#Rolling Volatility
df["Volatility"] = df["Daily Return (%)"].rolling(20).std()

#Business Use

#Market risk measure

#Previous Close
df["Previous Close"] = df["Close"].shift(1)

#Gap Up / Gap Down
df["Gap"] = df["Open"] - df["Previous Close"]

#Cumulative Return
df["Cumulative Return"]=(1+df["Daily Return (%)"]/100).cumprod()

#Positive Trading Days
df["Profit Day"]=df["Price Change"]>0

#Negative Trading Days
df["Loss Day"]=df["Price Change"]<0

#Bullish Day
df["Bullish"]=df["Close"]>df["Open"]

#Bullish Day
df["Bullish"]=df["Close"]>df["Open"]

#Check Dataset
df.head()

#Business KPIs

#KPI 1
#Total Trading Days
print("Total Trading Days :",len(df))

#KPI 2

#Highest Closing Price

print("Highest Close :",df["Close"].max())

#KPI 3

#Lowest Closing Price

print("Lowest Close :",df["Close"].min())

#Average Closing Price

print("Average Close :",round(df["Close"].mean(),2))

#KPI 5

#Highest Opening Price

print("Highest Open :",df["Open"].max())

#KPI 6

#Lowest Opening Price

print("Lowest Open :",df["Open"].min())

#KPI 7

#Highest Volume

print("Highest Volume :",df["Volume"].max())

#KPI 8

#Average Volume

print("Average Volume :",round(df["Volume"].mean(),2))

#KPI 9

#Highest Daily Gain

print("Highest Gain :",round(df["Daily Return (%)"].max(),2),"%")

#KPI 10

#Highest Daily Loss

print("Highest Loss :",round(df["Daily Return (%)"].min(),2),"%")

#KPI 11

#Average Daily Return

print("Average Return :",round(df["Daily Return (%)"].mean(),2),"%")

#KPI 12

#Average Daily Range

print("Average Daily Range :",round(df["Daily Range"].mean(),2))

#KPI 13

#Average Volatility

print("Average Volatility :",round(df["Volatility"].mean(),2))

#KPI 14

#Profit Days

print("Profit Days :",df["Profit Day"].sum())

#KPI 15

#Loss Days

print("Loss Days :",df["Loss Day"].sum())

#KPI 16

#Bullish Days

print("Bullish Days :",df["Bullish"].sum())

#KPI 17
#Bearish Days
df["Bearish"] = df["Close"] < df["Open"]
print("Bearish Days :",df["Bearish"].sum())

#ave Feature Engineered Dataset
df.to_csv("data/NIFTY50_Feature_Engineered.csv",index=False)

'''Business Insights

After this stage, we can answer:

How many trading days occurred?
When did the biggest daily gain happen?
When did the biggest daily loss happen?
What is the average return?
What is the average volatility?
How many bullish and bearish days were there?
What was the average trading range of the market?
How are moving averages behaving in terms of the long-term trend?'''

#Part 3 – Data Visualization & Business Insights

#Visualization 1 – Closing Price Trend
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Close"])

plt.title("NIFTY 50 Closing Price Trend")

plt.xlabel("Year")

plt.ylabel("Closing Price")

plt.show()

#Business Insight

''''The market shows a long-term upward trend.
Temporary corrections are also observed.'''

#Visualization 2 – Trading Volume Trend
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Volume"])

plt.title("Trading Volume Trend")

plt.xlabel("Year")

plt.ylabel("Volume")

plt.show()

#Business Insight
#High volume days major market events indicate

#Visualization 3 – Daily Return Distribution
plt.figure(figsize=(10,6))

sns.histplot(df["Daily Return (%)"],bins=50,kde=True)

plt.title("Daily Return Distribution")

plt.show()
'''Business Insight
Most daily returns 0% around clustered.
Extreme gains/losses occur.'''

#Visualization 4 – Closing Price Distribution
plt.figure(figsize=(10,6))

sns.histplot(df["Close"],bins=40,kde=True)

plt.title("Closing Price Distribution")

plt.show()

#Visualization 5 – Closing Price Boxplot
plt.figure(figsize=(8,5))

sns.boxplot(x=df["Close"])

plt.title("Closing Price Boxplot")

plt.show()
'''Business Insight
Outliers major bull runs may represent'''

#Visualization 6 – Monthly Average Closing Price
monthly=df.groupby("Month")["Close"].mean()

plt.figure(figsize=(12,6))

monthly.reindex([
"January","February","March","April","May","June",
"July","August","September","October","November","December"
]).plot(kind="bar")

plt.title("Monthly Average Closing Price")

plt.ylabel("Average Close")

plt.show()

#Visualization 7 – Year-wise Average Closing Price
year=df.groupby("Year")["Close"].mean()

plt.figure(figsize=(12,6))

year.plot(marker="o")

plt.title("Year-wise Average Close")

plt.show()

#Visualization 8 – Weekday Performance
weekday=df.groupby("Weekday")["Daily Return (%)"].mean()

weekday=weekday.reindex([
"Monday",
"Tuesday",
"Wednesday",
"Thursday",
"Friday"
])

plt.figure(figsize=(8,5))

weekday.plot(kind="bar")

plt.title("Average Daily Return by Weekday")

plt.show()
'''Business Insight
Identify which weekday performs best on average'''

#Visualization 9 – Quarterly Performance
quarter=df.groupby("Quarter")["Close"].mean()

plt.figure(figsize=(8,5))

quarter.plot(kind="bar")

plt.title("Quarter-wise Average Close")

plt.show()

#Visualization 10 – High vs Low Price
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["High"],label="High")

plt.plot(df["Date"],df["Low"],label="Low")

plt.legend()

plt.title("High vs Low Price")

plt.show()

#Visualization 11 – Open vs Close
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Open"],label="Open")

plt.plot(df["Date"],df["Close"],label="Close")

plt.legend()

plt.title("Open vs Close")

plt.show()

#Visualization 12 – Daily Trading Range
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Daily Range"])

plt.title("Daily Trading Range")

plt.show()

#Visualization 13 – Moving Average Analysis
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Close"],label="Close")

plt.plot(df["Date"],df["20 Day MA"],label="20 MA")

plt.plot(df["Date"],df["50 Day MA"],label="50 MA")

plt.legend()

plt.title("Moving Average Analysis")

plt.show()
'''Business Insight
Short-term aur medium-term trend comparision '''

#Visualization 14 – Volatility Trend
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Volatility"])

plt.title("20-Day Rolling Volatility")

plt.show()

#Visualization 15 – Cumulative Return
plt.figure(figsize=(15,6))

plt.plot(df["Date"],df["Cumulative Return"])

plt.title("Cumulative Return")

plt.show()

#Visualization 16 – Correlation Heatmap
plt.figure(figsize=(10,8))

sns.heatmap(
df.select_dtypes(include="number").corr(),
annot=True,
cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()
'''Business Insight
Price columns generally highly correlated hote hain.
Volume ka relationship alag observe ho sakta hai.'''

#Visualization 17 – Return Boxplot
plt.figure(figsize=(8,5))

sns.boxplot(x=df["Daily Return (%)"])

plt.title("Daily Return Boxplot")

plt.show()

#Visualization 18 – Top 10 Highest Gain Days
top_gain=df.nlargest(10,"Daily Return (%)")

plt.figure(figsize=(12,6))

sns.barplot(
data=top_gain,
x="Daily Return (%)",
y=top_gain["Date"].astype(str)
)

plt.title("Top 10 Gain Days")

plt.show()

#Visualization 19 – Top 10 Biggest Loss Days
top_loss=df.nsmallest(10,"Daily Return (%)")

plt.figure(figsize=(12,6))

sns.barplot(
data=top_loss,
x="Daily Return (%)",
y=top_loss["Date"].astype(str)
)

plt.title("Top 10 Loss Days")

plt.show()

#Visualization 20 – Bullish vs Bearish Days
counts=[
df["Bullish"].sum(),
df["Bearish"].sum()
]

plt.figure(figsize=(6,6))

plt.pie(
counts,
labels=["Bullish","Bearish"],
autopct="%1.1f%%"
)

plt.title("Bullish vs Bearish Days")

plt.show()

'''verall Business Insights
The NIFTY 50 shows a long-term upward trend despite temporary market corrections.
Daily returns are centered around zero, indicating normal day-to-day market fluctuations.
Some periods experience high volatility, usually during major market events or economic announcements.
Moving averages help identify short-term, medium-term, and long-term market trends.
Bullish trading sessions slightly outnumber bearish sessions over the long run.
Spikes in trading volume often coincide with significant price movements.
Year-over-year analysis indicates consistent long-term growth in the market.'''